version: '3.1'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teioc_password
      MYSQL_DATABASE: teioc
      MYSQL_USER: teioc_user
      MYSQL_PASSWORD: teioc_password
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
